
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product
          uri: lb://PRODUCT-MS
          predicates:
            - Path=/product-ms/**
          filters:
            - StripPrefix=1
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          jwk-set-uri: http://localhost:9990/realms/master/protocol/openid-connect/certs
server:
  port: 8987
